import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Inter, Roboto} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans', // <-- La asignamos a la variable que usa shadcn
});

// 3. Configura Roboto como una fuente opcional
const roboto = Roboto({
  weight: ['400', '700'], 
  subsets: ['latin'],
  variable: '--font-roboto', 
});

export const metadata: Metadata = {
  title: "Prospera Digital LLC | Consultorio Podológico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable, // Aplica la variable --font-sans
          roboto.variable // Aplica la variable --font-roboto
        )}
      >
        {children}
      </body>
    </html>
  );
}
